# Generated by Django 3.1 on 2021-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('limit_exceeded', models.BooleanField(default=False)),
                ('limit_exceeded_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('channel_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('thumbnail_default', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_high', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
